### ISSUE TITLE
Some Thoughts (maybe I'll work on them at some point)

### ISSUE THREAD

**Issue by jacobgb24** [byu-imaal/dohjs#1]
* [x] hint text for resolver is missing colon after `https`
* [x] Could have some common resolvers in a combobox as well
* [x] Method should be a combo box since there's only 2 options
* [ ] query type could also be a combo box, but with typing still
* [ ] include console error message in interface (looks like you'd have to hook the function)

* [ ] If there's a CORS error, automatically create CORS url and try again (notify user of change). Maybe this is insecure and not something that should be done. 
* [x] Could also be a checkbox to auto CORS-ify when needed.

**Comment by jacobgb24** [comment]
Thinking about it more, maybe when a CORS issue is detected, notify the user and present a button `Run again with CORS proxy` which when clicked modifies the resolver URL and sends the query. That avoids potential security concerns since it's a user decision

**Comment by kimbo** [comment]
>Thinking about it more, maybe when a CORS issue is detected, notify the user and present a button Run again with CORS proxy which when clicked modifies the resolver URL and sends the query. That avoids potential security concerns since it's a user decision

This is hard because I'm not sure how exactly to determine if the issue is a CORS error or some other error with the request. Maybe there's a way, but I haven't looked into it much.

**Comment by kimbo** [comment]
>include console error message in interface (looks like you'd have to hook the function)

This could be nice

**Comment by jacobgb24** [comment]
A really crappy way to do it is to just looks for `CORS` in the error message. (after you hooked the log)

**Comment by jacobgb24** [comment]
Most of this has been done in #2 (and improved in #3). Only thing left really is printing error message

**Comment by jacobgb24** [comment]
Per slack discussion, hooking logs does not reveal CORS issues. Thus, the majority of this issue has been completed. (The only other one is making a dropdown for qtype, but idk on the usefulness of that.)
