### ISSUE TITLE
<doh-img> tag

### ISSUE THREAD

**Issue by kimbo** [byu-imaal/dohjs#31]
Similar to `<doh-script>`, but to fetch images. We'll want to make `<doh-img>` allow usual img attributes (`alt`, `width`, `height`, etc) and just apply them to a child `<img>` element or something.

Example:
```html
<doh-img src="https://example.com/my-image.png" 
 resolver="https://example.com/dns-query" 
 alt="asdf"></doh-img>
```

This will require looking into correct accept headers for images.

**Comment by jacobgb24** [comment]
none of this is possible since we can't manually set the SNI when doing a request for a resource using an IP (e.g. `https://128.187.1.100/index.html`). They might just pull the SNI from the hostname (looks like NodeJS is doing this).
