### ISSUE TITLE
set global resolver for all <doh-script> and related tags

### ISSUE THREAD

**Issue by kimbo** [byu-imaal/dohjs#35]
Currently, you have to use the `resolver` attribute to specify the DoH resolver on a per-script basis.
It would be nice to be able to set a global DoH resolver for all the `<doh-script>` and any other `<doh-whatever>` tags on the page. Not sure how this would fit into dohjs, but I think it might be worth looking into.

**Comment by jacobgb24** [comment]
none of this is possible since we can't manually set the SNI when doing a request for a resource using an IP (e.g. `https://128.187.1.100/index.html`). They might just pull the SNI from the hostname (looks like NodeJS is doing this).
