### ISSUE TITLE
Find real-world examples of more obscure records / verify dns-packet code

### ISSUE THREAD

**Issue by jacobgb24** [byu-imaal/dohjs#38]
One concern right now is that we aren't entirely sure how dns-packet handles some of the more obscure records (e.g. DNSSEC records, HWINFO, SRV, ENDS). Knowing this would help us in certain cases like #13. 

This issue could be tackled two ways:
1. Verify how the dns-packet code works and create sample json responses for each record type.
2. Find real world servers that have these records available.

The second option may be a bit more useful, but I don't know of an easy way to go about it.

**Comment by visionm45** [comment]
i'm looking at the library for use with XMPP.  

a SRV request to  
_xmpp-client._tcp.example.com 
returns the default connection 

and a TXT request to  
_xmppconnect.example.com 
should return alternative connection methods.

i'm not sure if this is what you are looking for here but maybe it could be useful for you 

ex:
dig -t txt _xmppconnect.tigase.net    
dig -t SRV _xmpp-client._tcp.tigase.net
