### ISSUE TITLE
Support for URI queries?

### ISSUE THREAD

**Issue by draeder** [byu-imaal/dohjs#53]
I wasn't able to find URI queries in your API Documentation or examples. Does dohjs support this?

**Comment by kimbo** [comment]
We use https://github.com/mafintosh/dns-packet for all the DNS wire format encoding/decoding, and they don't have any special handling for that type like they do for others, but it's pretty easy to do with a few extra lines of code.

Here's a quick example:

```javascript
const doh = require('dohjs');

const resolver = new doh.DohResolver('https://dns.google/dns-query');

// 256 is URI rrtype (see https://tools.ietf.org/html/rfc7553#section-4.1)
// we do UNKNOWN_<type> b/c of https://github.com/mafintosh/dns-packet/blob/master/types.js#L101
let qtype = "UNKNOWN_256";
let qname = "31110.cp.bortzmeyer.fr.";

resolver.query(qname, qtype).then(response => {
    response.answers.forEach(ans => {
        let priority = ans.data.readUint16BE(0);
        let weight = ans.data.readUint16BE(2);
        let uri = ans.data.toString("utf-8", 4, ans.data.length);
        console.log(ans.name, ans.ttl, ans.class, ans.type, priority, weight, uri);
    });
});
```

If you were feeling motivated, it probably wouldn't be that much work to submit a PR to mafintosh/dns-packet to support URI RRs out of the box.

**Comment by draeder** [comment]
Thank you - I ultimately found that TXT records are what I wanted to use, so I moved away from URI. But should I or anyone else need it, it's nice to have this workaround.
