### ISSUE TITLE
Uncaught TypeError: can't access property "length", buf is undefined if nameserver_url is invalid

### ISSUE THREAD

**Issue by defkev** [byu-imaal/dohjs#56]
If the nameserver_url is invalid (e.g. https://cloudflare-dns.com/dns-query-wrong) causing the server to return a non-200 (e.g. 404) DoHjs will error out with an unhandled type error causing makeQuery to never resolve nor reject.

You can test it on dohjs.org making any query to an invalid nameserver_url

Would be useful to reject the promise so i can handle the error accordingly without a try/catch

**Comment by kimbo** [comment]
Thanks for submitting this! I'll potentially get a minute to look tomorrow

**Comment by kimbo** [comment]
Could you provide a small code snippet so I know exactly where this error is happening?

**Comment by defkev** [comment]
As i said, you can test it on https://dohjs.org

`

**Comment by defkev** [comment]
Just upgraded to 0.3.2 and can confirm as fixed.
Tho the error handling, especially on HTTP errors as in the OP example, could be improved.

e.g. a query to https://cloudflare-dns.com/dns-query-wrong will return the entire raw response payload as a string instead of a proper error object:
```
Failed to parse DNS packet: RangeError: Trying to access beyond buffer length, raw response body: <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>cloudflare-lb</center>
</body>
</html>
```
Which is ultimately unusable for further progressing unless i start parsing the html (which we all know is hard) and try to extract information from it.

Either pass the entire response object (403 Forbidden in this case) down to sendDohMsg or return a generic error like you already do with network errors:

`TypeError: NetworkError when attempting to fetch resource.`

The latter can be presented to the user, the former can't without raising eyebrows ;)
