### ISSUE TITLE
Feature request: DNSSEC validation

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [byu-imaal/dohjs#57]
This is an incredibly useful library, but it still appears to leave the *verification of* RRSIG records to the application. Would/might/could this be considered in-scope?

(My use-case / the reason I'm interested in DoH in the first place is so I can access and inspect DNS data from a WebExtension, to check things like CAA and TLSA records against active connections.)

**Comment by kimbo** [comment]
That sounds like a cool use case, thanks for sharing. DNSSEC validation is
certainly useful. Unfortunately it'd be a significant amount of work to
implement, I don't personally have much expertise in the ins and outs of
it, and I don't know of any existing JavaScript libraries that do DNSSEC
validation.

If someone were to come forward with some well-tested DNSSEC validation
code, we might consider adding it to dohjs (no promises). Other than that
I'd say it's out of scope.

One (probably ridiculous) option is to try using emscripten to port
libunbound to JavaScript or something of that nature.

**Comment by JamesTheAwesomeDude** [comment]
> If someone were to come forward with some well-tested DNSSEC validation
> code, we might consider adding it to dohjs (no promises). Other than that
> I'd say it's out of scope.

Interesting; thanks for the response. I take it the first few Google results for "javascript dnssec library" seemed wanting?

I'll drop a link to [one javascript library's implementation](https://github.com/netkicorp/dnssecjs/blob/master/lib/dnssec-verifier.js) and [the C implementation used by `dig`](https://gitlab.isc.org/isc-projects/bind9/-/blob/main/lib/dns/zoneverify.c), then, for future reference. Getting it written is one matter, making the codebase mature is another, however; so I'll close this issue for now.
