### ISSUE TITLE
show different visualization color for DNSSEC-only versus DNSSEC+DANE

### ISSUE THREAD

**Issue by adrelanos** [byu-imaal/dohjs#72]
Currently:

* domains which only have DNSSEC are visualized with a green color padlock in the right side of the URL but.
* domains which have DNSSEC+DANE are also visualized with a green color padlock in the right side of the URL.

This is non-ideal. Now when I want to find out which one is it, I have to click the padlock to then see the popup saying DNSSEC or DNSSEC secured + DANE valid.

Feature request: Could you please show a different visualization that communicates that DNSSEC is good but DANE (which as DNSSEC as a prerequisite) is better?

Since very few websites currently are DANE secured, it would be nice if this add-on could contribute the encourage getting the best possible security (DANE) visualization. Maybe one or another user would contact the site owner and suggest adding DANE. Your add-on has certainly motivated me to start working on adding DANE support for all websites where I am a sysadmin, thank you!

Suggestion:

* DNSSEC-only domains: keep the currently used light green padlock
* DNSSEC+DANE domains: use a darker green, perhaps a bigger green field spelling out `DANE`

The implementation specifics (colors, styles) on how to have visual distinction are of course just the first thing coming to mind. If there are better ways to illustrate it, even better.

**Comment by adrelanos** [comment]
I found a screenshot how [DNSSEC Checker](https://chrome.google.com/webstore/detail/dnssec-checker/amebjlfjmmeflkjhcealhbekaljgnekg) is doing a better visualization.

https://lh3.googleusercontent.com/eRUj44jFdmEKV_JwnMyd5avcvr6mrGRJRnnHBZIyqxLMS2LaSk2Cr_2Ju8y5ZINCzRW9EUjYEX9wMAyq13zY_wUEmg

(Should above link break, I recommend to go to the original link [DNSSEC Checker](https://chrome.google.com/webstore/detail/dnssec-checker/amebjlfjmmeflkjhcealhbekaljgnekg) and view the screenshots.)

Better than what I had in mind. A shield symbol (could also be a lock symbol) with two colors. Upper side is blue, lower side is green. Blue isn't as great a color as green (in context of security) and far away from red but good to show something "special", that is DNSSEC-only. The two different parts of the shield symbol diagonally separated by some white space and a red line.

**Comment by adrelanos** [comment]
Yet another solution would be to always have two different icons. Maybe a shield symbol for DNSSEC and a padlock symbol for DANE. Probably better than my above idea.

**Comment by jacobgb24** [comment]
Hi @adrelanos could you clarify if this issue is for dohjs.org or another website? I'm not exactly sure where you're seeing this icon

**Comment by adrelanos** [comment]
Sorry, I posted in the wrong repository.

**Comment by jacobgb24** [comment]
Ok no problem!
